/*  
    Euler Project
    #2

    Problem:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    Find the sum of all the even-valued terms in the sequence which do not exceed four million.

    
    Mauro Parra-Miranda
    mauropm@gmail.com
*/

#define LIMIT 4000000

#include <stdio.h> 

main(){ 
  int _1st = 1; 
  int _2nd = 2;
  int tmp = 0; 
  long int old_sum = 0;
  long int new_sum = 0;
  while(_2nd<LIMIT){ 
    //printf("%ld\n",old_sum); 
    //printf("%d, %d\n", _1st, _2nd);
    if ( (_2nd%2==0) ) { 
      new_sum = old_sum + _2nd; 
    }
    //if (new_sum<LIMIT) 
      old_sum=new_sum;
    tmp = _1st + _2nd; 
    _1st = _2nd; 
    _2nd = tmp; 
    printf("%d, %d\n", _1st, _2nd);
  }
  printf("%ld\n",old_sum); 
}
